CREATE DATABASE IF NOT EXISTS librevies
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE librevies;

CREATE TABLE IF NOT EXISTS membre (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(50) NOT NULL,
  motdepasse VARCHAR(255) NOT NULL,
  email VARCHAR(254) NOT NULL,
  valider TINYINT(1) NOT NULL DEFAULT 0,
  droit TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_membre_pseudo (pseudo),
  UNIQUE KEY uq_membre_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
